language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source

script:
  - ./vendor/bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=5eecaf38fad60eb4fd578e492b7cc4a877cb236802c1159dfa12ec15fb88e952 ./vendor/bin/test-reporter
